version: "3.7"

volumes:
  eshopdb:
  eshop:

services:
  eshopdb:
    image: mysql:5.7
    volumes:
    - eshopdb:/var/lib/mysql
    ports:
      - '3306'
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file: .env
  eshop:
    build: .
    volumes:
      - eshop:/usr/src/eshop
    ports:
      - '8000:8000'
    depends_on:
      - eshopdb
    environment:
      - DJANGO_SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_USERNAME=${SUPERUSER_NAME}
      - DJANGO_SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
    env_file: .env
